apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-management
  template:
    metadata:
      labels:
        app: course-management
    spec:
      containers:
        - name: course-management
          # Replace with your Docker Hub username
          image: jaskaran/course-management-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: MONGODB_URI
              value: "mongodb://<your-mongodb-host>:<port>/languageLearningDB"
            # Add other environment variables as needed
