apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: NodePort
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
